load("@bazel_skylib//lib:paths.bzl", "paths")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

package(default_visibility = ["//visibility:public"])

exports_files(["BUILD.bazel"])

filegroup(
    name = "standard-yang",
    srcs = glob(["*.yang"]),
)

filegroup(
    name = "common-yang",
    srcs = glob(["common/*.yang"]),
)

filegroup(
    name = "extensions-yang",
    srcs = glob(["extensions/*.yang"]),
)

filegroup(
    name = "annotation-yang",
    srcs = glob(["annotations/*.yang"]),
)

filegroup(
    name = "sonic-yang",
    srcs = glob(["sonic/*.yang"]),
)

filegroup(
    name = "sonic-common-yang",
    srcs = glob(["sonic/common/*.yang"]),
)

genrule(
    name = "generate-yangs",
    srcs = [
        ":standard-yang",
        ":common-yang",
        ":extensions-yang",
        ":annotation-yang",
        ":sonic-yang",
        ":sonic-common-yang",
    ],
    outs = [
        "yangs.tar",
    ],
    cmd = """
          mkdir yang yang/common yang/extensions yang/annotations yang/sonic yang/sonic/common
          for f in $(locations :standard-yang); do
              cp $$f yang/
          done
          for f in $(locations :common-yang); do
              cp $$f yang/common
          done
          for f in $(locations :extensions-yang); do
              cp $$f yang/extensions
          done
          for f in $(locations :annotation-yang); do
              cp $$f yang/annotations/
          done
          for f in $(locations :sonic-yang); do
              cp $$f yang/sonic
          done
          for f in $(locations :sonic-common-yang); do
              cp $$f yang/sonic/common
          done
          tar --sort=name --mtime='1970-01-01' --owner=0 --group=0 -cf $(@D)/yangs.tar yang/
          """,
    visibility = ["//visibility:public"],
)

filegroup(
    name = "yang_mod_files",
    srcs = glob(["*.yang"]),
)

filegroup(
    name = "yang_mod_ext_files",
    srcs = glob(["extensions/*.yang"]),
)

filegroup(
    name = "yang_annotation_files",
    srcs = glob(["annotations/*.yang"]),
)

filegroup(
    name = "yang_ietf_mod_ext_files",
    srcs = glob(["extensions/ietf-*.yang"], allow_empty = True),
)

filegroup(
    name = "yang_common_files",
    srcs = glob(["common/*.yang"]),
)

filegroup(
    name = "_models_test",
    srcs = glob(["testdata/*.yang"], allow_empty = True),
)

pkg_tar(
    name = "models_test_tar",
    srcs = [":_models_test"],
    mode = "0755",
    package_dir = "/usr/models/yang",
)

filegroup(
    name = "yang",
    srcs = glob(
        ["**/*.yang"],
        exclude = glob(["**/*-annot.yang"]),
    ),
)

write_file(
    name = "yang_annotations",
    out = "api_ignore",
    content = [
        "# Yangs ignored",
    ] + [
        "{0}".format(paths.basename(v))
        for v in glob(
            ["**/*-annot.yang"],
            exclude = ["testdata/**"],
        )
    ] + ["\n"],
    newline = "unix",
    # TODO(b/239426591) maybe include sonic-extensions.yang too?
)

filegroup(
    name = "_models",
    srcs = glob(
        ["**/*.yang"],
        exclude = ["testdata/**"],
    ),
)

pkg_tar(
    name = "models_tar",
    srcs = [
        "version.xml",
        ":_models",
        "//config/transformer:files",
    ],
    mode = "0755",
    package_dir = "/usr/models/yang",
)

filegroup(
    name = "all-yang",
    srcs = glob(["**/*"]),
)

genrule(
    name = "sonic-yang-tree",
    srcs = [
        "yangs.tar",
    ],
    outs = [
        "sonic_allyangs_tree.txt",
        "sonic_allyangs_tree.html",
    ],
    cmd_bash = "tar xf $(location yangs.tar) && " +
               "cp yang/common/* yang/sonic/common/ && " +
               "./$(location //tools/pyang:tree) " +
               "    --text=sonic_allyangs_tree.txt " +
               "    --html=sonic_allyangs_tree.html " +
               "    -p ./yang/sonic " +
               "    -c ./yang/sonic/common " +
               "    --annotpath=./yang/annotations && " +
               "cp sonic_allyangs_tree.txt  $(location sonic_allyangs_tree.txt) && " +
               "cp sonic_allyangs_tree.html $(location sonic_allyangs_tree.html)",
    tools = ["//tools/pyang:tree"],
    visibility = ["//visibility:public"],
)

genrule(
    name = "yang-tree",
    srcs = [
        "yangs.tar",
    ],
    outs = [
        "oc_yang_tree.txt",
        "oc_yang_tree.html",
    ],
    cmd_bash = "tar xf $(location yangs.tar) && " +
               "rm -rf yang/sonic && " +
               "./$(location //tools/pyang:tree) " +
               "    --text=oc_yang_tree.txt " +
               "    --html=oc_yang_tree.html " +
               "    -p ./yang/ " +
               "    -c ./yang/common " +
               "    --annotpath=./yang/annotations && " +
               "cp oc_yang_tree.txt  $(location oc_yang_tree.txt) && " +
               "cp oc_yang_tree.html $(location oc_yang_tree.html)",
    tools = ["//tools/pyang:tree"],
    visibility = ["//visibility:public"],
)
