load("@pip_sonic_mgmt_common//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "generate_yin",
    srcs = ["generate_yin.py"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("lxml"),
        requirement("pyang"),
    ],
)
