load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cs",
    srcs = [
        "cs.go",
        "cs_abort.go",
        "cs_commit.go",
        "cs_cphist.go",
        "cs_ds.go",
        "cs_exit.go",
        "cs_getdb.go",
        "cs_kill.go",
        "cs_mesg.go",
        "cs_session.go",
        "cs_start.go",
        "cs_status.go",
        "cs_tx.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/translib/cs",
    visibility = ["//visibility:public"],
    deps = [
        "//translib/db",
        "//translib/log",
        "//translib/tlerr",
        "//translib/transformer",
        "@com_github_golang_glog//:glog",
    ],
)

alias(
    name = "go_default_library",
    actual = ":cs",
    visibility = ["//visibility:public"],
)

go_test(
    name = "cs_test",
    srcs = [
        "cs_session_test.go",
        "cs_test.go",
    ],
    data = [
        "//tools/test:database_config.json",
        "//cvl/conf:cvl_cfg.json",
    ],
    embed = [":cs"],
    env = {
        "DB_CONFIG_PATH": "tools/test/database_config.json",
        "CVL_CFG_FILE": "cvl/conf/cvl_cfg.json",
    },
    rundir = ".",
    visibility = ["//visibility:public"],
    deps = ["//translib/db"],
)
