load("@pip_sonic_mgmt_common//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "pyang_plugins",
    srcs = glob(["*.py"]),
    visibility = ["//visibility:public"],
    deps = [
        requirement("lxml"),
    ],
)

exports_files(["BUILD.bazel"])
