load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "yparser",
    srcs = [
        "ly_path.go",
        "yparser.go",
    ],
    cdeps = [
        "@com_github_cesnet_libyang//:libyang",
    ],
    cgo = True,
    importpath = "github.com/Azure/sonic-mgmt-common/cvl/internal/yparser",
    visibility = ["//cvl:__subpackages__"],
    deps = ["//cvl/internal/util"],
)

alias(
    name = "go_default_library",
    actual = ":yparser",
    visibility = ["//cvl:__subpackages__"],
)
