load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "apis",
    srcs = [
        "db_diff.go",
        "notify.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/translib/internal/apis",
    visibility = ["//translib:__subpackages__"],
    deps = [
        "//translib/db",
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_ygot//ygot",
    ],
)

alias(
    name = "go_default_library",
    actual = ":apis",
    visibility = ["//translib:__subpackages__"],
)

go_test(
    name = "apis_test",
    srcs = ["db_diff_test.go"],
    data = [
        "//tools/test:database_config.json",
        "//cvl/conf:cvl_cfg.json",
    ],
    embed = [":apis"],
    env = {
        "DB_CONFIG_PATH": "tools/test/database_config.json",
        "CVL_CFG_FILE": "cvl/conf/cvl_cfg.json",
    },
    rundir = ".",
    deps = ["//translib/db"],
)
