load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "translib",
    srcs = [
        "acl_app.go",
        "app_interface.go",
        "app_utils.go",
        "authorize.go",
        "common_app.go",
        "lldp_app.go",
        "path_utils.go",
        "pfm_app.go",
        "request_binder.go",
        "subscribe.go",
        "subscribe_app_interface.go",
        "subscribe_app_utils.go",
        "subscribe_notify.go",
        "subscribe_utils.go",
        "sys_app.go",
        "translib.go",
        "version.go",
        "yanglib_app.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/translib",
    visibility = ["//visibility:public"],
    deps = [
        "//cvl",
        "//translib/db",
        "//translib/internal/apis",
        "//translib/log",
        "//translib/ocbinds",
        "//translib/path",
        "//translib/tlerr",
        "//translib/transformer",
        "//translib/utils",
        "@com_github_golang_glog//:glog",
        "@com_github_kylelemons_godebug//pretty",
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_goyang//pkg/yang",
        "@com_github_openconfig_ygot//util",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
        "@com_github_workiva_go_datastructures//queue",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)

# Integration test requiring Redis, CVL schemas, and SONiC platform infrastructure.
# Run with: bazel test //translib:translib_test --test_tag_filters=
go_test(
    name = "translib_test",
    srcs = [
        "acl_app_test.go",
        "app_utils_test.go",
        "path_utils_test.go",
        # Removing platform test since our implementation of platforms is different.
        #"pfm_app_test.go",
        "request_binder_test.go",
        "subscribe_test.go",
        "translib_test.go",
        "version_test.go",
        "yanglib_app_test.go",
    ],
    data = [
        "//tools/test:database_config.json",
        "//cvl/conf:cvl_cfg.json",
    ],
    embed = [":translib"],
    env = {
        "DB_CONFIG_PATH": "tools/test/database_config.json",
        "CVL_CFG_FILE": "cvl/conf/cvl_cfg.json",
    },
    rundir = ".",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [
        "//translib/db",
        "//translib/ocbinds",
        "//translib/tlerr",
        "@com_github_golang_glog//:glog",
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_workiva_go_datastructures//queue",
    ],
)

alias(
    name = "go_default_library",
    actual = ":translib",
    visibility = ["//visibility:public"],
)
