load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "util",
    srcs = [
        "luascript_util.go",
        "util.go",
    ],
    cdeps = [
        "@com_github_cesnet_libyang//:libyang",
    ],
    cgo = True,
    importpath = "github.com/Azure/sonic-mgmt-common/cvl/internal/util",
    visibility = ["//cvl:__subpackages__"],
    deps = [
        "//translib/log",
        "@com_github_golang_glog//:glog",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_workiva_go_datastructures//set",
    ],
)

alias(
    name = "go_default_library",
    actual = ":util",
    visibility = ["//cvl:__subpackages__"],
)
