load("@pip_sonic_mgmt_common//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")

py_binary(
    name = "generate_yang",
    srcs = ["generate_yang.py"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("jinja2"),
    ],
)

py_binary(
    name = "import_yang",
    srcs = ["import_yang.py"],
    visibility = ["//visibility:public"],
    deps = [
        requirement("pyang"),
    ],
)

py_binary(
    name = "tree",
    srcs = [
        "tree.py",
        "yangtools.py",
    ],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//tools/pyang/pyang_plugins",
        requirement("pyang"),
    ],
)
