load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

LIB_SRCS = [
    "emitjson.go",
    "emitjson_select.go",
    "emitjson_sort.go",
    "oc.go",
    "schema.go",
]

go_library(
    name = "ocbinds",
    srcs = LIB_SRCS,
    importpath = "github.com/Azure/sonic-mgmt-common/translib/ocbinds",
    visibility = ["//visibility:public"],
    deps = [
        "//translib/log",
        "@com_github_golang_glog//:glog",
        "@com_github_maruel_natural//:natural",
        "@com_github_openconfig_goyang//pkg/yang",  #keep
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)

go_test(
    name = "ocbinds_test",
    srcs = [
        "emitjson_sort_test.go",
        "emitjson_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":ocbinds"],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_ygot//ygot",
        "@com_github_openconfig_ygot//ytypes",
    ],
)

pkg_tar(
    name = "ocbinds_tar",
    srcs = LIB_SRCS,
    mode = "0755",
    package_dir = "/sonic/src/sonic-mgmt-common/translib/ocbinds",
    visibility = ["//visibility:public"],
)

genrule(
    name = "oc_go",
    srcs = ["//models/yang:yangs.tar"],
    outs = ["oc.go"],
    cmd = "tar xf $(location //models/yang:yangs.tar) && " +
          "mkdir to_use && " +
          "find ./yang -name *.yang -exec mv {} to_use/ \\; && " +
          "rm -rf to_use/*-annot.yang && " +
          "./$(location @com_github_openconfig_ygot//generator) -generate_fakeroot -output_file $@ -package_name ocbinds -generate_fakeroot -fakeroot_name=device -compress_paths=false -exclude_modules ietf-interfaces -path . to_use/*yang",
    tools = ["@com_github_openconfig_ygot//generator"],
)

alias(
    name = "go_default_library",
    actual = ":ocbinds",
    visibility = ["//visibility:public"],
)
